#!/usr/bin/php
<?php
/**
 * Sysconf - Interactive configuration system for PHP applications
 * Copyright (C) 2012 by iHMS Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @category    iHMS
 * @package     iHMS_Sysconf
 * @copyright   2012 by iHMS Team
 * @author      Laurent Declercq <l.declercq@nuxwin.com>
 * @version     0.0.1
 * @link        https://github.com/i-HMS/sysconf Sysconf Home Site
 * @license     http://www.gnu.org/licenses/gpl-2.0.html GPL v2
 */

/***********************************************************************************************************************
 * DESCRIPTION
 *
 * Module scanner script. This is only intented to test the sysconf-preconfigure script.
 *
 * A real scanner will parse a module archive to extract both template and config file into a temporary directory and
 * will print the following information on STDOUT:
 *
 * module: Module name
 * version: Installed version if any
 * templates: path to extracted templates file
 * config: path to extracted config file
 *
 * Beacause this scanner is only for tests, it's will extract nothing but simply mimic a scanner behavior by writing
 * some config files and their associated template files into a temporary directory.
 */

$tmpDir = '/tmp/sysconf';

if (!file_exists($tmpDir) && !@mkdir($tmpDir, 0755, true)) {
    fwrite(STDERR, "Unable to create {$tmpDir} directory: " . join(' ', error_get_last()) . "\n");
    exit(1);
}

array_shift($argv);

foreach ($argv as $module) {
    $version = '0.0.1';
    $templatePath = "$tmpDir/$module.templates";
    $configPath = "$tmpDir/$module.config";

    $templateContent = <<<EOF
Template: $module/boolean
Type: boolean
Default: true
Description: Do you like the $module module?
 This is a template test for the $module module.
EOF;

    $configContent = <<<EOF
#!/usr/bin/php
<?php

// Include ConfModule client
require_once '/home/nuxwin/Bureau/working/sysconf/iHMS/Sysconf/Client/ConfModule.php';

\$module = explode('.', basename(\$argv[0]));

input('high', "{\$module[0]}/boolean");
go();

// Purge of sysconf database since it's only a test
purge();

exit(0);
EOF;

    // Write templates file
    $fh = fopen($templatePath, 'w');
    fwrite($fh, $templateContent);
    fclose($fh);

    // Write config file
    $fh = fopen($configPath, 'w');
    fwrite($fh, $configContent);
    fclose($fh);

    echo "$module 0.0.1 " . "$templatePath " . "$configPath", "\n";
}

exit(0);
