#!/usr/bin/php
<?php
/**
 * Sysconf - Interactive configuration system for PHP applications
 * Copyright (C) 2012 by iHMS Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @category    iHMS
 * @package     iHMS_Sysconf
 * @copyright   2012 by iHMS Team
 * @author      Laurent Declercq <l.declercq@nuxwin.com>
 * @version     0.0.1
 * @link        https://github.com/i-HMS/sysconf Sysconf Home Site
 * @license     http://www.gnu.org/licenses/gpl-2.0.html GPL v2
 */
/***********************************************************************************************************************
 * DESCRIPTION
 *
 * ihms-preconfigure demo script. This is more a regression/stress test than other thing.
 *
 * Important: We run this demo in noninteractive mode to avoid the user to press enter again and again (by default, 150
 * confmodules are created and run...). If you want run this test with other FrontEnd such dialog,  you can set a lower
 * value for number of confmodules to create and set the SYSCONF_FRONTEND environement variable. for instance:
 *
 * SYSCONF_FRONTEND=dialog php preconfigure-test 2
 *
 * will create 2 confmodule (rather than 150) and use Dialog FronTend.
 */

$scannerTest = __DIR__ . '/preconfigure/scanner';

// Show user information if we are in noninteractive mode
if (getenv('SYSCONF_FRONTEND') === false) {
    putenv('SYSCONF_DEBUG=user');
}

$fp = popen("ihms-preconfigure --ihms -s {$scannerTest} -f noninteractive", 'w');

$itemNb = (isset($argv[1]) && preg_match('/^\d+$/', $argv[1])) ? $argv[1] : 150;

for ($x = 0; $x < $itemNb; $x++) {
    fwrite($fp, "module{$x}\n");
}

pclose($fp);
@rmdir('/tmp/sysconf');

exit(0);
